name: Build and Push ethgas_commit and related images

on:
  push:
    tags:
      - "v*"
    paths:
      - crates/pbs/src/mev_boost/get_header.rs
      - crates/common/src/interop/*

jobs:
  build-ethgas-commit:
    uses: ./.github/workflows/ethgas-base.yml
    with:
      image_name: commitboost_ethgas_pbs
      dockerfile: provisioning/pbs.Dockerfile
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}