name: Build and Push ethgas_pbs

on:
  push:
    tags:
      - "v*"
    paths:
      - crates/pbs/src/mev_boost/get_header.rs
      - crates/common/src/interop/*
      - Cargo.toml

jobs:
  build-ethgas-pbs:
    uses: ./.github/workflows/ethgas-base.yml
    with:
      image_name: commitboost_ethgas_pbs
      dockerfile: provisioning/pbs.ethgas.Dockerfile
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}